export const FETCH_START = 'PRODUCT_FETCH_START';
export const FETCH_FAIL = 'PRODUCT_FETCH_FAIL';
export const PRODUCT_FETCHED = 'PRODUCT_FETCHED';
export const PRODUCT_SAVED = 'PRODUCT_SAVED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';
export const PRODUCTS_LIST_FETCHED = 'PRODUCTS_LIST_FETCHED';